captainVersion: 4

services:
  $$cap_appname-mongo:
    image: $$cap_mongo_image
    volumes:
      - $$cap_appname-mongo-data:/data/db
      - $$cap_appname-mongo-logs:/data/logs
      - $$cap_appname-mongo-conf:/etc/mongo
    command: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/mongo-init.sh; docker-entrypoint.sh mongod --wiredTigerCacheSizeGB 1 --auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: $$cap_mongo_root_user
      MONGO_INITDB_ROOT_PASSWORD: $$cap_mongo_root_password
      MONGO_INITDB_DATABASE: openim_v3
      TZ: Europe/Paris
    caproverExtra:
      notExposeAsWebApp: true

  $$cap_appname-redis:
    image: $$cap_redis_image
    volumes:
      - $$cap_appname-redis-data:/data
      - $$cap_appname-redis-config:/usr/local/redis/config
    command: ["redis-server", "/usr/local/redis/config/redis.conf", "--requirepass", "$$cap_redis_password", "--appendonly", "yes"]
    environment:
      TZ: Europe/Paris
    caproverExtra:
      notExposeAsWebApp: true

  $$cap_appname-etcd:
    image: $$cap_etcd_image
    environment:
      ETCD_NAME: s1
      ETCD_DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER: s1=http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_TOKEN: tkn
      ETCD_INITIAL_CLUSTER_STATE: new
    ports:
      - 12379:2379
      - 12380:2380
    caproverExtra:
      notExposeAsWebApp: true

  $$cap_appname-openim-server:
    image: $$cap_openim_server_image
    ports:
      - $$cap_openim_msg_gateway_port:10001
      - $$cap_openim_api_port:10002
    environment:
      IMENV_MONGODB_ADDRESS: $$cap_mongo_address
      IMENV_MONGODB_USERNAME: $$cap_mongo_root_user
      IMENV_MONGODB_PASSWORD: $$cap_mongo_root_password
      IMENV_REDIS_ADDRESS: $$cap_redis_address
      IMENV_REDIS_PASSWORD: $$cap_redis_password
      IMENV_ETCD_ADDRESS: $$cap_etcd_address
      IMENV_LOG_LEVEL: info
    caproverExtra:
      containerHttpPort: 10002

  $$cap_appname-openim-chat:
    image: $$cap_openim_chat_image
    ports:
      - $$cap_openim_chat_port:10008
    environment:
      CHATENV_MONGODB_ADDRESS: $$cap_mongo_address
      CHATENV_MONGODB_USERNAME: $$cap_mongo_root_user
      CHATENV_MONGODB_PASSWORD: $$cap_mongo_root_password
      CHATENV_REDIS_ADDRESS: $$cap_redis_address
      CHATENV_REDIS_PASSWORD: $$cap_redis_password
      CHATENV_LOG_LEVEL: info
    caproverExtra:
      containerHttpPort: 10008

caproverOneClickApp:
  variables:
    - id: $$cap_mongo_image
      label: MongoDB Image
      defaultValue: mongo:5.0
      validRegex: /.{1,}/

    - id: $$cap_redis_image
      label: Redis Image
      defaultValue: redis:6.2
      validRegex: /.{1,}/

    - id: $$cap_etcd_image
      label: Etcd Image
      defaultValue: bitnami/etcd:3.5
      validRegex: /.{1,}/

    - id: $$cap_openim_server_image
      label: OpenIM Server Image
      defaultValue: openim/server:latest
      validRegex: /.{1,}/

    - id: $$cap_openim_chat_image
      label: OpenIM Chat Image
      defaultValue: openim/chat:latest
      validRegex: /.{1,}/

    - id: $$cap_mongo_root_user
      label: MongoDB Root Username
      defaultValue: root
      validRegex: /^[a-zA-Z0-9]+$/

    - id: $$cap_mongo_root_password
      label: MongoDB Root Password
      defaultValue: $$cap_gen_random_hex(16)
      validRegex: /.{8,}/

    - id: $$cap_redis_password
      label: Redis Password
      defaultValue: $$cap_gen_random_hex(16)
      validRegex: /.{8,}/

    - id: $$cap_mongo_address
      label: MongoDB Address
      defaultValue: srv-captain--$$cap_appname-mongo:27017
      validRegex: /.{1,}/

    - id: $$cap_redis_address
      label: Redis Address
      defaultValue: srv-captain--$$cap_appname-redis:6379
      validRegex: /.{1,}/

    - id: $$cap_etcd_address
      label: Etcd Address
      defaultValue: srv-captain--$$cap_appname-etcd:2379
      validRegex: /.{1,}/

    - id: $$cap_openim_msg_gateway_port
      label: OpenIM Gateway Port
      defaultValue: 10001
      validRegex: /^\d+$/

    - id: $$cap_openim_api_port
      label: OpenIM API Port
      defaultValue: 10002
      validRegex: /^\d+$/

    - id: $$cap_openim_chat_port
      label: OpenIM Chat Port
      defaultValue: 10008
      validRegex: /^\d+$/

  instructions:
    start: |-
      Deploy OpenIM with this one-click app template. Make sure to configure all the variables correctly for your setup.
    end: |-
      Your OpenIM services have been successfully deployed! Access the OpenIM server at the configured ports.
  displayName: OpenIM
  isOfficial: false
  description: Deploy OpenIM using CapRover with MongoDB, Redis, and Etcd.
  documentation: https://open-im.github.io
